plugins {
    id "com.android.application" version "8.5.2" apply false
}

subprojects {
    configurations.configureEach {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:1.9.24"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.24"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24"
            force "androidx.activity:activity:1.9.3"
            force "androidx.core:core:1.13.1"
            force "androidx.core:core-ktx:1.13.1"
        }
    }
}
